feature_weights:
  Job: 0.2
  MBTI: 0.2
  Hobby: 0.2
  Age: 0.1
  Height: 0.1
  Weight: 0.1
  Tags: 0.3

text_columns:
  - "My answer"

tag_options:
  My answer:
    - "한식"
    - "일식"
    - "중식"
    - "이탈리아 음식"
    - "퓨전음식"
    - "BBQ"
    - "Seafood"
    - "Brunch"
    - "Cafe"
    - "Bars"
    - "전통음식"
    - "Fine Dining"
    - "Cozy"
    - "Scenic View"
    - "Casual"
    - "Street Food"
    - "서울"
    - "부산"
    - "인천"
    - "경기"
    - "수원"
    - "대구"
    - "제주"
    - "강원"
    - "동해"
    - "속초"
    - "Subway Near"
    - "Vegan/Vegetarian"
    - "Spicy"
    - "Local Favorite"  
    - "Highly Rated"
    - "Hidden Gem"
    - "사회복지"
    - "공공기관"
    - "공무원"
    - "의료"
    - "재무/회계"
    - "금융/영업"
    - "마케팅/광고"
    - "IT/개발"
    - "HR"
    - "교육"
    - "미디어/콘텐츠"
    - "요식업"
    - "기획/행사"
    - "법률"
    - "e커머스"
    - "기타"
    - "운동/헬스"
    - "여행/드라이브"
    - "맛집/카페 투어"
    - "전시회/문화생활"
    - "영화/드라마/애니"
    - "음악/노래"
    - "게임/보드게임"
    - "자기계발/공부"
    - "독서"
    - "사진/필름 카메라"
    - "술/와인/위스키"
    - "요리/플레이팅"
    - "아웃도어/캠핑"
    - "스포츠 관전"
    - "스포츠 플레이"
    - "댄스/퍼포먼스"
    - "방탈출/TRPG"
    - "리더성향"
    - "문화생활"
    - "유머"
    - "배려심"
    - "운동"
    - "여행/탐험"
    - "대화/소통"
    - "맛집 투어"
    - "소규모 모임"
    - "취미"
    - "긍정적 성격"
    - "활발한 성격"
    - "편안한 만남"
    - "공통 직무/전문분야"
    - "자기계발/성장 지향"
    - "음악/영화 취향 공유"
    - "일상속 낭만"
    - "동네친구"