text_columns:
  - "My restaurant"

tag_options:
  My restaurant:
    - "Korean"
    - "Japanese"
    - "Chinese"
    - "Italian"
    - "Fusion"
    - "BBQ"
    - "Seafood"
    - "Brunch"
    - "Cafe"
    - "Bars"
    - "Traditional"
    - "Fine Dining"
    - "Cozy"
    - "Scenic View"
    - "Casual"
    - "Street Food"
    - "Seoul"
    - "Busan"
    - "Incheon"
    - "Gyeonggi"
    - "Subway Near"
    - "Vegan/Vegetarian"
    - "Spicy"
    - "Local Favorite"  
    - "Highly Rated"
    - "Hidden Gem"